sudo: required
service:
    - docker

before_install:
    - docker build -t prashaant9986/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run prashaant9986/react-test npm test --  --coverage

after_success:
    - docker build -t prashaant9986/multi-client ./client
    - docker build -t prashaant9986/multi-nginx ./nginx
    - docker build -t prashaant9986/multi-server ./server
    - docker build -t prashaant9986/multi-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push prashaant9986/multi-client 
    - docker push prashaant9986/multi-nginx 
    - docker push prashaant9986/multi-server 
    - docker push prashaant9986/multi-worker 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-1"
    app: "multi-docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-1-057034942296"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"





